[
  {
    title: "Luxury Apartment in Mumbai",
    budget: 25000000,
    propertyStatus: "For Sale",
    bedroom: 3,
    address: "Marine Drive, Mumbai",
    description: "A spacious luxury apartment with stunning sea views.",
    features: ["Sea View", "Balcony", "Swimming Pool"],
    propertySize: "Large",
    propertyType: "Apartment",
    garage: true,
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    pincode: "400002",
    area: 2000,
    buildYear: 2015,
    bathrooms: 3,
    location: "Marine Drive",
  },
  {
    title: "Cozy 2BHK in Latur",
    budget: 5000000,
    propertyStatus: "For Rent",
    bedroom: 2,
    address: "Shivaji Nagar, Latur",
    description: "A well-maintained 2BHK apartment available for rent.",
    features: ["Furnished", "Close to Market", "Parking Available"],
    propertySize: "Medium",
    propertyType: "Apartment",
    garage: false,
    city: "Latur",
    state: "Maharashtra",
    country: "India",
    pincode: "413512",
    area: 1100,
    buildYear: 2010,
    bathrooms: 1,
    location: "Shivaji Nagar",
  },
  {
    title: "Penthouse in Delhi",
    budget: 45000000,
    propertyStatus: "For Sale",
    bedroom: 4,
    address: "Connaught Place, Delhi",
    description: "Luxurious penthouse with private terrace and jacuzzi.",
    features: ["Terrace", "Jacuzzi", "Gymnasium"],
    propertySize: "Large",
    propertyType: "Penthouse",
    garage: true,
    city: "Delhi",
    state: "Delhi",
    country: "India",
    pincode: "110001",
    area: 3500,
    buildYear: 2018,
    bathrooms: 4,
    location: "Connaught Place",
  },
  {
    title: "2BHK Flat in Pune",
    budget: 12000000,
    propertyStatus: "For Sale",
    bedroom: 2,
    address: "Kothrud, Pune",
    description: "Modern 2BHK flat with garden space and modern amenities.",
    features: ["Garden", "Gym", "Security"],
    propertySize: "Medium",
    propertyType: "Apartment",
    garage: true,
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    pincode: "411038",
    area: 1400,
    buildYear: 2020,
    bathrooms: 2,
    location: "Kothrud",
  },
  {
    title: "Studio Apartment in Aurangabad",
    budget: 3000000,
    propertyStatus: "For Rent",
    bedroom: 1,
    address: "MG Road, Aurangabad",
    description: "Affordable studio apartment for rent, close to amenities.",
    features: ["Fully Furnished", "Air Conditioning"],
    propertySize: "Small",
    propertyType: "Apartment",
    garage: false,
    city: "Aurangabad",
    state: "Maharashtra",
    country: "India",
    pincode: "431001",
    area: 500,
    buildYear: 2012,
    bathrooms: 1,
    location: "MG Road",
  },
  {
    title: "4BHK House in Latur",
    budget: 15000000,
    propertyStatus: "For Sale",
    bedroom: 4,
    address: "Ravi Nagar, Latur",
    description: "Spacious independent house with a large garden and garage.",
    features: ["Garden", "Garage", "Security System"],
    propertySize: "Large",
    propertyType: "House",
    garage: true,
    city: "Latur",
    state: "Maharashtra",
    country: "India",
    pincode: "413512",
    area: 2500,
    buildYear: 2008,
    bathrooms: 3,
    location: "Ravi Nagar",
  },
  {
    title: "Commercial Space in Pune",
    budget: 30000000,
    propertyStatus: "For Sale",
    bedroom: 0,
    address: "Hinjewadi, Pune",
    description:
      "Prime location commercial space for office or retail purposes.",
    features: ["High Foot Traffic", "Parking", "Lift"],
    propertySize: "Very Large",
    propertyType: "Commercial",
    garage: true,
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    pincode: "411057",
    area: 5000,
    buildYear: 2022,
    bathrooms: 2,
    location: "Hinjewadi",
  },
  {
    title: "3BHK House in Mumbai Suburbs",
    budget: 18000000,
    propertyStatus: "For Sale",
    bedroom: 3,
    address: "Andheri West, Mumbai",
    description: "Beautiful house with a large garden and swimming pool.",
    features: ["Swimming Pool", "Garden", "Parking"],
    propertySize: "Large",
    propertyType: "House",
    garage: true,
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    pincode: "400053",
    area: 2200,
    buildYear: 2017,
    bathrooms: 3,
    location: "Andheri West",
  },
  {
    title: "1BHK Apartment in Delhi",
    budget: 8000000,
    propertyStatus: "For Rent",
    bedroom: 1,
    address: "Saket, Delhi",
    description: "Affordable 1BHK apartment for rent in a quiet area.",
    features: ["Fully Furnished", "Security"],
    propertySize: "Small",
    propertyType: "Apartment",
    garage: false,
    city: "Delhi",
    state: "Delhi",
    country: "India",
    pincode: "110017",
    area: 600,
    buildYear: 2016,
    bathrooms: 1,
    location: "Saket",
  },
];
